export const QUESTION_ACTION_TYPE = {
    FETCH_QUESTION_LIST: 'FETCH_QUESTION_LIST',
    FETCH_QUESTION_LIST_SUCCESS: 'FETCH_QUESTION_LIST_SUCCESS',
    FETCH_QUESTION_LIST_FAILED: 'FETCH_QUESTION_LIST_FAILED',
}